has(daily_diet1,avocado_toast,[white_bread-30,avocado-20,olive_oil-5]).
has(daily_diet1,vegetable_sticks_with_hummus,[hummus-60,carrot-50,cucumber-50,bell_peppers-50,celery-50]).
has(daily_diet1,beef_and_broccoli_stir_fry,[beef-100,broccoli-100,garlic-5,ginger-5,sesame_oil-5,white_rice-70]).
has(daily_diet1,almond_butter_on_whole_wheat_crackers,[almond_butter-20,crackers-30]).
has(daily_diet1,veggie_pizza,[pizza_dough-150,tomato_sauce-30,mozzarella_cheese-40,bell_peppers-30,porcini_mushroom-30,onion-15,olives_black-20]).
has(daily_diet1,avocado_toast,[white_bread-30,avocado-20,olive_oil-5]).
has(daily_diet1,vegetable_sticks_with_hummus,[hummus-66,carrot-50,cucumber-50,bell_peppers-50,celery-50]).
has(daily_diet1,beef_and_broccoli_stir_fry,[beef-100,broccoli-100,garlic-5,ginger-5,sesame_oil-5,white_rice-70]).
has(daily_diet1,almond_butter_on_whole_wheat_crackers,[almond_butter-20,crackers-30]).
has(daily_diet1,veggie_pizza,[pizza_dough-150,tomato_sauce-30,mozzarella_cheese-40,bell_peppers-30,porcini_mushroom-30,onion-15,olives_black-20]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-20,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
has(daily_diet2,pancakes_and_maple_syrup,[pancakes-30,maple_syrup-5]).
has(daily_diet2,chocolate_chip_cookies,[shortcrust_pastry-10,chocolate_chips-2]).
has(daily_diet2,grilled_chicken_salad,[chicken-70,lettuce-80,tomato-50,cucumber-50,red_onion-22,olives_green-20,feta_cheese-20]).
has(daily_diet2,sliced_apples_with_peanut_butter,[apple-20,peanut_butter-10]).
has(daily_diet2,grilled_vegetable_platter,[bell_peppers-60,zucchini-70,eggplant-70,tomato-50,onion-50,olive_oil-10,garlic-5]).
